name: lovelace
channels:
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - matplotlib-base
  - matplotlib-inline
  - numpy
  - pandas
  - py-xgboost=2.0.3=cpu_pyheee7c3a_4
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn=0.13.2=hd8ed1ab_0
  - seaborn-base=0.13.2=pyhd8ed1ab_0
  - shap
  - streamlit=1.35.0
